project_id = "zvnhlxiugbbahgmbfixe"

[functions.extract]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.track-analytics]
verify_jwt = false

[functions.submit-poster]
verify_jwt = false

[functions.notify-admin-moderation]
verify_jwt = false
